### ISSUE TITLE
No ' - ' sign / negative values accepted

### ISSUE THREAD

**Issue by SebiderSushi** [pejic/Summation#4]
I'd like to be able to add negtive Values to the List...

**Comment by pejic** [comment]
I had not realized, thanks! I've enabled negative values in v0.1.2. It will take around a day or two for F-Droid to publish the new version.

**Comment by SebiderSushi** [comment]
Awesome, i didn't even expect an answer this quick, but you already fixed it. +1

**Comment by SebiderSushi** [comment]
F-Droid doesn't seem to get the new version...

**Comment by pejic** [comment]
Sorry about that. Thanks for letting me know about the F-Droid issue. I will get back to when I find out what's going on.

**Comment by pejic** [comment]
It was my mistake: I had failed to push the version's tag to github. So while F-Droid would have seen new commits, it looks for new tags which weren't there.

I have now pushed the new tag. So F-Droid should pick up on it soon.

Thanks again for pointing out the missing version.

**Comment by SebiderSushi** [comment]
No problem. Thanks for being so quick with all this stuff.
